import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import {NextIntlClientProvider} from 'next-intl';
import { Toaster } from "@/components/ui/sonner";
import BreadcrumbApp from "@/components/ui/breadcrumb-app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    other: [
      {
        rel: "stylesheet",
        url: "https://cdn-uicons.flaticon.com/3.0.0/uicons-thin-rounded/css/uicons-thin-rounded.css"
      }
    ]
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <SidebarProvider>
            <AppSidebar />

            <section className="w-full flex flex-col min-h-screen gap-2">
              <BreadcrumbApp />

              {children}
            </section>

            <Toaster />
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
